services:
  server:
    image: node:alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      DATABASE_URL: "mysql://root:password@server-db-1/app"
      JWT_SECRET: "supersecretkey"
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app

volumes:
  db-data: