version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=mysql
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
      - PORT=3000  
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "3000:3000"  
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
